### PR TITLE
Fix for RT#108082

### PR DESCRIPTION
**Pull request by draxil**
I've packaged up changes for:

https://rt.cpan.org/Public/Bug/Display.html?id=108082

Included adding a test to the examples and removing one from the should fail list.

### CODE REVIEW

**Comment by jhoblitt** [comment]
The test counts need to be updated.

**Comment by draxil** [comment]
Yes! Not quite sure how I didn't see that,  but.. done.

**Comment by draxil** [comment]
@jhoblitt Anything else I can do to help get this accepted?

**Comment by jhoblitt** [comment]
Nope!  I missed that the PR had been updated!

**Comment by draxil** [comment]
Thanks!

**Comment by jhoblitt** [comment]
I'm trying to get a new release out... battling module install failures.

**Comment by draxil** [comment]
That'd be fantastic. If you ever need any grunt-work don't hesitate to ask.

**Comment by kyzn** [comment]
Hi! Do you have any updates on whether this patch (0.09) will be released to CPAN soon?
Thanks!

**Comment by draxil** [comment]
Yes please!
If there's anything I could do to help out please let me know.

**Pull request merged**
